### ISSUE TITLE
txindex error

### ISSUE THREAD

**Issue by ChineseGeek** [janoside/btc-rpc-explorer#303] opened 2021-04-09 00:44 UTC
I upgraded btc-rpc-explorer to v3.0.0 and in Node Details > Blockchain I see txindex with a red X, but i have txindex=1 in my bitcoin.conf

**Comment by shesek** [comment] 2021-04-09 01:11
This is likely because you're using Bitcoin Core older than v0.21.0, which did not have the `getindexinfo` rpc command. A workaround for this is planned for the next btc-rpc-explorer release. See #300 for more details.

**Comment by shesek** [comment] 2021-04-09 01:15
Hmm, actually, it seems that v3.0.0 reports (incorrectly) that txindex is disabled on https://explorer.btc21.org/node-details, with Bitcoin Core v0.21.0. So something else is probably going on. cc @janoside

**Comment by janoside** [comment] 2021-04-09 02:04
I believe this is addressed by the above commit. Demo site looks right now.

The cause was calling `getindexinfo` "too early" before we used the result of `getblockchaininfo` to know the node version (used to decide whether `getindexinfo` is supported...so it was assumed not to be).

I still want to quickly get the concept from #300 done, but this should work for now.

@ChineseGeek Please report back if the issue is not fixed.

**Closed by janoside** 2021-04-09 02:04 UTC
