### ISSUE TITLE
Internal Server Errror when trying to select transaction data

### ISSUE THREAD

**Issue by Ruben-Repo** [janoside/btc-rpc-explorer#75] opened 2018-11-28 18:59 UTC
message: 'Internal Server Error',
    body: 'Work queue depth exceeded',
    code: 500,
    name: 'RpcError' } } reason: { RpcError: Internal Server Error
    at Client.rpc (/home/ruben/Explorer/btc-rpc-explorer/node_modules/bitcoin-core/dist/src/parser.js:73:13)
    at Client.tryCatcher (/home/ruben/Explorer/btc-rpc-explorer/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ruben/Explorer/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ruben/Explorer/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ruben/Explorer/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ruben/Explorer/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/home/ruben/Explorer/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:638:18)
    at Request._callback (/home/ruben/Explorer/btc-rpc-explorer/node_modules/bluebird/js/release/nodeback.js:45:21)
    at Request.self.callback (/home/ruben/Explorer/btc-rpc-explorer/node_modules/request/request.js:185:22)
    at Request.emit (events.js:187:15)
    at Request.<anonymous> (/home/ruben/Explorer/btc-rpc-explorer/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/ruben/Explorer/btc-rpc-explorer/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)

**Comment by janoside** [comment] 2018-11-28 19:02
@Ruben-Repo Thanks for the report. Looks to be a duplicate of #49.

**Closed by janoside** 2018-11-28 19:02 UTC

**Comment by Ruben-Repo** [comment] 2018-11-28 19:10
Error computing total input/output values for tx: err=TypeError: Cannot read property 'length' of undefined, tx={"message":"No such mempool transaction. Use -txindex to enable blockchain transaction queries. Use gettransaction for wallet transactions.","code":-5,"name":"RpcError"}, txInputs={}, blockHeight=483624
GET /block-height/483624 500 6728.743 ms - 15191


Sorry to Trouble you but gets me an error 500 on each click.

**Comment by janoside** [comment] 2018-11-28 20:12
Hi @Ruben-Repo - It looks like you need to do some further configuration of your node. Specifically, this error message is indicating that your node is NOT configured with txindex=1, which is a requirement to use this tool. Check out some docs for how to configure your node on your specific OS and try this tool again after your configuration includes txindex=1.

**Comment by ridicula** [comment] 2018-11-29 11:50
Thanks. The transaction index was missing for the ones I tried. Reindexed them and the issue is fixed. 

But still I get 500 errors when i try a GET request on  /block-height/364404. Some blocks work, some dont. 

Below is the error displayed on the browser window
`
Error
/home/ruben/Explorer/btc-rpc-explorer/views/includes/transaction-io-details.pug:10 8| if (txInputs) 9| - var extraInputCount = 0; > 10| each txVin, txVinIndex in tx.vin 11| if (!txVin.coinbase) 12| - var vout = null; 13| if (txInputs && txInputs[txVinIndex]) Cannot read property 'length' of undefined

TypeError: /home/ruben/Explorer/btc-rpc-explorer/views/includes/transaction-io-details.pug:10
    8| 		if (txInputs)
    9| 			- var extraInputCount = 0;
  > 10| 			each txVin, txVinIndex in tx.vin
    11| 				if (!txVin.coinbase)
    12| 					- var vout = null;
    13| 					if (txInputs && txInputs[txVinIndex])

Cannot read property 'length' of undefined
    at eval (eval at wrap (/home/ruben/Explorer/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1127:32)
    at eval (eval at wrap (/home/ruben/Explorer/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1490:4)
    at eval (eval at wrap (/home/ruben/Explorer/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2762:4)
    at template (eval at wrap (/home/ruben/Explorer/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:3187:72)
    at Object.exports.renderFile (/home/ruben/Explorer/btc-rpc-explorer/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/home/ruben/Explorer/btc-rpc-explorer/node_modules/pug/lib/index.js:417:21)
    at exports.__express (/home/ruben/Explorer/btc-rpc-explorer/node_modules/pug/lib/index.js:464:11)
    at View.app.engine (/home/ruben/Explorer/btc-rpc-explorer/app.js:40:23)
    at View.render (/home/ruben/Explorer/btc-rpc-explorer/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/ruben/Explorer/btc-rpc-explorer/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/ruben/Explorer/btc-rpc-explorer/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/ruben/Explorer/btc-rpc-explorer/node_modules/express/lib/response.js:1008:7)
    at /home/ruben/Explorer/btc-rpc-explorer/routes/baseActionsRouter.js:425:8
    at process._tickCallback (internal/process/next_tick.js:68:7)
`
