### ISSUE TITLE
mempool not showing all 1-4sat/byte transactions

### ISSUE THREAD

**Issue by pwpwpwpw** [janoside/btc-rpc-explorer#245] opened 2020-10-24 14:33 UTC
Hey, the mempool never shows correct values, when I check https://explorer.btc21.org/mempool-summary it's always different, right now I have 6200 tranasction and the official site shows 13000. Mostly the transactions in the 1-4sat/byte range are not shown for me, the rest seem to be ok.

 - Bitcoin Core 0.20.1 / Electrs 0.8.5
 - NodeJS Version 10.22.1
 - Browser Chrome 86
 - Code Version 2.0.2 / Commit e0aa751
 
bitcoin.conf 
txindex=1
server=1
proxy=127.0.0.1:port
listen=1
bind=127.0.0.1
onlynet=onion 

btc-rpc-explorer environment configuration
BTCEXP_HOST=0.0.0.0
BTCEXP_BITCOIND_COOKIE=/mnt/sdb1/.bitcoin/.cookie
BTCEXP_ADDRESS_API=electrumx
BTCEXP_ELECTRUMX_SERVERS=tcp://0.0.0.0:port
BTCEXP_UI_SHOW_TOOLS_SUBHEADER=true

**Comment by janoside** [comment] 2020-12-23 17:09
@pwpwpwpw I'm curious - when you see the transaction-count discrepancy between your explorer and the public demo explorer: does what displays at `/mempool-summary` on your local explorer match the `Pending Tx` number shown on the homepage of your local explorer?

**Comment by pwpwpwpw** [comment] 2020-12-24 01:27
@janoside Yes, the local page shows pending Tx same as the /mempool-summary, it's about 2100 tx right now, on your site it's 33k tx. I thought this was an installation problem so I formatted my machine and got a fresh install (I actually did that twice this year and the same bug) but same thing. Any idea how to find the cause of this?

**Comment by janoside** [comment] 2021-01-05 18:26
@pwpwpwpw Got it. Since the homepage summary shows the same number as the `/mempool-summary` page, I'm fairly confident this is due to some configuration with your `bitcoind`. Let's try this next: on your local `btc-rpc-explorer` go to the URL `/rpc-browser?method=getmempoolinfo` and hit the "Execute" button. That will return the basic mempool info, including the number of entries, the memory size, and, most importantly, some configuration info from your `bitcoind` node: "maxmempool", "mempoolminfee", and "minrelaytxfee".

Currently, the values for my public demo `bitcoind` are:

    "maxmempool": 300000000
    "mempoolminfee": 0.00001
    "minrelaytxfee": 0.00001

If the values returned from your node are different than these, we'll have the answer about why your mempool looks different than the public demo, and the next step would just be to change these values in your `bitcoind` config.

**Comment by janoside** [comment] 2021-01-19 17:49
@pwpwpwpw Any update on this?

**Comment by pwpwpwpw** [comment] 2021-01-20 01:59
@janoside Sorry, I didn't get any notification that you replied, weird.

[
    {
        "loaded": true,
        "size": 3477,
        "bytes": 1414143,
        "usage": 6031504,
        "maxmempool": 300000000,
        "mempoolminfee": 0.00001,
        "minrelaytxfee": 0.00001
    }
]

It returns this, so it's the same as yours but the mempool doesn't have 3477 tx, it has 31k. What next?

**Comment by janoside** [comment] 2021-01-21 20:27
Hmm, well that sucks. Honestly we're reaching the limits of my knowledge here. I'm surprised that your node is seeing such dramatically lower mempool txs without any clear explanation (given my knowledge).

One other thing that piques my curiosity is the line `onlynet=onion` - I'm curious how many active peers you have and what the quality/speed of your connection to them is. I really have no clue whether this is a reasonable thought, but if you have a small number of poor connections I can imagine that your node is just failing to receive all of the unconfirmed transactions. (As I finish writing this idea out, it feels more farfetched than when I first imagined it!... but I'll throw it out there anyway). To give this idea a quick check you might go to `/node-status` in your explorer and check the "Network Traffic" section and see how that looks.

I wish I could solve this for you but I think I'll need to refer you "up the chain" to someone with more knowledge about Bitcoin Core's functioning here.

I'm going to close this because I don't feel I have anything else I can offer you (sorry). But, if you figure it out I'd be happy to hear what the issue was. Likewise, if I stumble on any other relevant info I'll keep this issue in mind and add to it.

**Closed by janoside** 2021-01-21 20:27 UTC
Labels: bug

**Comment by pwpwpwpw** [comment] 2021-01-22 00:17
@janoside yeah that's not it, initially it's a bit slow to find connections but after about 10 minutes I always have 10 connections+, so it's not that.
