### ISSUE TITLE
Error Socket Hung Up

### ISSUE THREAD

**Issue by ConanDW** [janoside/btc-rpc-explorer#80] opened 2018-12-06 23:51 UTC
code: 'ECONNRESET' } stack: Error; socket hung up
  at createHangupError 9_http_client.js:3423;15)
at Socket.socketOnEnd 

Wont run after this. have put in the correct RPC credentials. Could use some help please.

**Comment by janoside** [comment] 2019-02-05 21:16
Duplicate of #51 after rename.

**Closed by janoside** 2019-02-05 21:16 UTC
