### ISSUE TITLE
Show duplicate miner name ( Data Section) in mining summary

### ISSUE THREAD

**Issue by odomdev** [janoside/btc-rpc-explorer#350] opened 2021-06-27 05:57 UTC
It is the same issue.Show duplicate miner name ( Data Section) in mining summary in safari but chrome and Firefox is ok.

Please give commit url that you fixed in GitHub to for verification.

**Comment by haykoreis** [comment] 2021-06-28 19:16
Duplicate of # yes

**Comment by odomdev** [comment] 2021-07-28 03:26
Hi @janoside any update?

**Comment by janoside** [comment] 2021-07-28 19:16
Please, when submitting bug reports, include more information...

What version are you running? And, for an issue like this, please include a screenshot to help with diagnosis.

**Comment by janoside** [comment] 2021-07-31 16:28
Closing this for lack of details. Feel free to add more information if you wish.

**Closed by janoside** 2021-07-31 16:28 UTC
Labels: bug
