### ISSUE TITLE
Predicted next block. Round fee rates to zero decimals.

### ISSUE THREAD

**Issue by pointbiz** [janoside/btc-rpc-explorer#340] opened 2021-06-03 00:48 UTC
**Describe the new feature or enhancement**
Just testing the pre-release with Core 0.19.1

I think it's easier to read if you round the fee rates in the new predicted block section to zero decimal places.

**Comment by janoside** [comment] 2021-06-03 19:08
@pointbiz I don't want to lose the precision since there are many cases where it can be relevant for someone sending a transaction to see a more precise estimate of what's able to get confirmed in the next block. For example: as I look right now, the minimum is "1.18 sat/vB" and if it was rounded down to "1" I could be confused into thinking "1.00 sat/vB" are set to be confirmed in the next block.

As a compromise I made a tweak to "visually mute" the decimals on this display. The tweak is live on the demo site. Happy to hear your feedback. I'm closing this since I'm trying to clean up issues right now, but happy to continue discussing.

**Closed by janoside** 2021-06-03 19:08 UTC
Labels: enhancement

**Comment by pointbiz** [comment] 2021-06-03 20:07
Ok. That makes sense. I wasn't sure it was intentional. Now I see the reasoning. Thanks.
